// Generated by tools/generate-sounds.mjs; edit the authored recipes there.
export const SOUND_DEFINITIONS = {
    "connection_connected": {
        "label": "Connected",
        "category": "Connection",
        "character": "Soft console contact with a short full confirmation body",
        "duration": 0.21,
        "priority": 2,
        "cooldown": 100
    },
    "connection_reconnected": {
        "label": "Reconnected",
        "category": "Connection",
        "character": "Shorter light contact with a compact settled body",
        "duration": 0.135,
        "priority": 2,
        "cooldown": 100
    },
    "connection_disconnected": {
        "label": "Disconnected",
        "category": "Connection",
        "character": "Single damped closure with a rounded soft attack",
        "duration": 0.16,
        "priority": 2,
        "cooldown": 100
    },
    "connection_lost": {
        "label": "Connection lost",
        "category": "Connection",
        "character": "Interrupted coarse contact and a muted second stop",
        "duration": 0.225,
        "priority": 3,
        "cooldown": 100
    },
    "connection_reconnecting": {
        "label": "Reconnecting",
        "category": "Connection",
        "character": "Quiet single neutral status contact",
        "duration": 0.11,
        "priority": 1,
        "cooldown": 5000
    },
    "connection_failed": {
        "label": "Connection failed",
        "category": "Connection",
        "character": "Dry rejected contact with a dense low body",
        "duration": 0.18,
        "priority": 3,
        "cooldown": 100
    },
    "server_error": {
        "label": "Server action error",
        "category": "Connection",
        "character": "Two compact dry refusal ticks",
        "duration": 0.145,
        "priority": 3,
        "cooldown": 100
    },
    "own_channel_join": {
        "label": "Joined channel",
        "category": "Your channel",
        "character": "Soft voice-path contact with a short rounded confirmation tail",
        "duration": 0.185,
        "priority": 2,
        "cooldown": 100
    },
    "own_channel_switch": {
        "label": "Switched channel",
        "category": "Your channel",
        "character": "Muted transition contact followed by a small firmer contact",
        "duration": 0.15,
        "priority": 2,
        "cooldown": 100
    },
    "own_channel_leave": {
        "label": "Left channel",
        "category": "Your channel",
        "character": "Single felt-damped closure with a short final decay",
        "duration": 0.12,
        "priority": 2,
        "cooldown": 100
    },
    "user_join": {
        "label": "User joined",
        "category": "Other users",
        "character": "Quiet clean presence tick",
        "duration": 0.09,
        "priority": 0,
        "cooldown": 180
    },
    "user_leave": {
        "label": "User left",
        "category": "Other users",
        "character": "Related presence tick with a softer damped edge",
        "duration": 0.095,
        "priority": 0,
        "cooldown": 180
    },
    "user_move_in": {
        "label": "User moved in",
        "category": "Other users",
        "character": "Small paired contacts with a clean second edge",
        "duration": 0.13,
        "priority": 0,
        "cooldown": 180
    },
    "user_move_out": {
        "label": "User moved out",
        "category": "Other users",
        "character": "Related paired contacts ending in a damped edge",
        "duration": 0.135,
        "priority": 0,
        "cooldown": 180
    },
    "mic_on": {
        "label": "Microphone on",
        "category": "Voice controls",
        "character": "Small clean control-surface contact",
        "duration": 0.07,
        "priority": 1,
        "cooldown": 100
    },
    "mic_off": {
        "label": "Microphone off",
        "category": "Voice controls",
        "character": "Muted control-surface release",
        "duration": 0.075,
        "priority": 1,
        "cooldown": 100
    },
    "deafen_on": {
        "label": "Deafened",
        "category": "Voice controls",
        "character": "Cushioned double contact with dark filtering",
        "duration": 0.12,
        "priority": 1,
        "cooldown": 100
    },
    "deafen_off": {
        "label": "Undeafened",
        "category": "Voice controls",
        "character": "Matching double contact with a clearer open edge",
        "duration": 0.125,
        "priority": 1,
        "cooldown": 100
    },
    "ptt_on": {
        "label": "Push-to-talk on",
        "category": "Voice controls",
        "character": "Tiny dry talkback contact",
        "duration": 0.028,
        "priority": 1,
        "cooldown": 0
    },
    "ptt_off": {
        "label": "Push-to-talk off",
        "category": "Voice controls",
        "character": "Tiny damped talkback release",
        "duration": 0.034,
        "priority": 1,
        "cooldown": 0
    },
    "mention": {
        "label": "Mention",
        "category": "Notifications",
        "character": "Defined single desktop tap with a brief supporting body",
        "duration": 0.165,
        "priority": 2,
        "cooldown": 100
    },
    "keyword": {
        "label": "Keyword highlight",
        "category": "Notifications",
        "character": "Compact textured tap with a softened attack",
        "duration": 0.12,
        "priority": 1,
        "cooldown": 100
    },
    "dm": {
        "label": "Direct message",
        "category": "Notifications",
        "character": "Two close dry desk contacts",
        "duration": 0.185,
        "priority": 1,
        "cooldown": 100
    },
    "channel_message": {
        "label": "Channel message",
        "category": "Notifications",
        "character": "Very quiet single muted tick",
        "duration": 0.085,
        "priority": 0,
        "cooldown": 250
    },
    "whisper": {
        "label": "Voice whisper",
        "category": "Notifications",
        "character": "Close dry soft contact and a tiny adjacent contact",
        "duration": 0.14,
        "priority": 2,
        "cooldown": 100
    },
    "poke": {
        "label": "Poke",
        "category": "Notifications",
        "character": "One firm controlled physical tap",
        "duration": 0.115,
        "priority": 2,
        "cooldown": 100
    },
    "join_leave": {
        "label": "Join/leave (your channel)",
        "category": "Notifications",
        "character": "Small neutral presence contact",
        "duration": 0.1,
        "priority": 0,
        "cooldown": 250
    },
    "buddy_online": {
        "label": "Watched contact online",
        "category": "Notifications",
        "character": "Warmer, slightly fuller presence contact",
        "duration": 0.15,
        "priority": 1,
        "cooldown": 100
    },
    "kick": {
        "label": "Kick/ban",
        "category": "Notifications",
        "character": "Firm low contact with a short abrupt cushioned stop",
        "duration": 0.155,
        "priority": 3,
        "cooldown": 100
    },
    "ban": {
        "label": "Banned",
        "category": "Notifications",
        "character": "Low dry stop followed by a subdued final contact",
        "duration": 0.22,
        "priority": 3,
        "cooldown": 100
    },
    "announcement": {
        "label": "Announcement",
        "category": "Notifications",
        "character": "Broader clean contact with a brief dry body",
        "duration": 0.24,
        "priority": 3,
        "cooldown": 100
    },
    "channel_watch": {
        "label": "Channel watch",
        "category": "Notifications",
        "character": "Quiet separated pair of damped status ticks",
        "duration": 0.15,
        "priority": 0,
        "cooldown": 250
    }
};
export const SOUND_URLS = {
    connection_connected: new URL("./assets/sounds/connection_connected.wav", import.meta.url).href,
    connection_reconnected: new URL("./assets/sounds/connection_reconnected.wav", import.meta.url).href,
    connection_disconnected: new URL("./assets/sounds/connection_disconnected.wav", import.meta.url).href,
    connection_lost: new URL("./assets/sounds/connection_lost.wav", import.meta.url).href,
    connection_reconnecting: new URL("./assets/sounds/connection_reconnecting.wav", import.meta.url).href,
    connection_failed: new URL("./assets/sounds/connection_failed.wav", import.meta.url).href,
    server_error: new URL("./assets/sounds/server_error.wav", import.meta.url).href,
    own_channel_join: new URL("./assets/sounds/own_channel_join.wav", import.meta.url).href,
    own_channel_switch: new URL("./assets/sounds/own_channel_switch.wav", import.meta.url).href,
    own_channel_leave: new URL("./assets/sounds/own_channel_leave.wav", import.meta.url).href,
    user_join: new URL("./assets/sounds/user_join.wav", import.meta.url).href,
    user_leave: new URL("./assets/sounds/user_leave.wav", import.meta.url).href,
    user_move_in: new URL("./assets/sounds/user_move_in.wav", import.meta.url).href,
    user_move_out: new URL("./assets/sounds/user_move_out.wav", import.meta.url).href,
    mic_on: new URL("./assets/sounds/mic_on.wav", import.meta.url).href,
    mic_off: new URL("./assets/sounds/mic_off.wav", import.meta.url).href,
    deafen_on: new URL("./assets/sounds/deafen_on.wav", import.meta.url).href,
    deafen_off: new URL("./assets/sounds/deafen_off.wav", import.meta.url).href,
    ptt_on: new URL("./assets/sounds/ptt_on.wav", import.meta.url).href,
    ptt_off: new URL("./assets/sounds/ptt_off.wav", import.meta.url).href,
    mention: new URL("./assets/sounds/mention.wav", import.meta.url).href,
    keyword: new URL("./assets/sounds/keyword.wav", import.meta.url).href,
    dm: new URL("./assets/sounds/dm.wav", import.meta.url).href,
    channel_message: new URL("./assets/sounds/channel_message.wav", import.meta.url).href,
    whisper: new URL("./assets/sounds/whisper.wav", import.meta.url).href,
    poke: new URL("./assets/sounds/poke.wav", import.meta.url).href,
    join_leave: new URL("./assets/sounds/join_leave.wav", import.meta.url).href,
    buddy_online: new URL("./assets/sounds/buddy_online.wav", import.meta.url).href,
    kick: new URL("./assets/sounds/kick.wav", import.meta.url).href,
    ban: new URL("./assets/sounds/ban.wav", import.meta.url).href,
    ban: new URL("./assets/sounds/ban.wav", import.meta.url).href,
    announcement: new URL("./assets/sounds/announcement.wav", import.meta.url).href,
    channel_watch: new URL("./assets/sounds/channel_watch.wav", import.meta.url).href,
};
export const SOUND_EVENTS = Object.keys(SOUND_DEFINITIONS);
export const SOUND_EVENT_GROUPS = [
    {
        "label": "Connection",
        "events": [
            [
                "connection_connected",
                "Connected"
            ],
            [
                "connection_reconnected",
                "Reconnected"
            ],
            [
                "connection_disconnected",
                "Disconnected"
            ],
            [
                "connection_lost",
                "Connection lost"
            ],
            [
                "connection_reconnecting",
                "Reconnecting"
            ],
            [
                "connection_failed",
                "Connection failed"
            ],
            [
                "server_error",
                "Server action error"
            ]
        ]
    },
    {
        "label": "Your channel",
        "events": [
            [
                "own_channel_join",
                "Joined channel"
            ],
            [
                "own_channel_switch",
                "Switched channel"
            ],
            [
                "own_channel_leave",
                "Left channel"
            ]
        ]
    },
    {
        "label": "Other users",
        "events": [
            [
                "user_join",
                "User joined"
            ],
            [
                "user_leave",
                "User left"
            ],
            [
                "user_move_in",
                "User moved in"
            ],
            [
                "user_move_out",
                "User moved out"
            ]
        ]
    },
    {
        "label": "Voice controls",
        "events": [
            [
                "mic_on",
                "Microphone on"
            ],
            [
                "mic_off",
                "Microphone off"
            ],
            [
                "deafen_on",
                "Deafened"
            ],
            [
                "deafen_off",
                "Undeafened"
            ],
            [
                "ptt_on",
                "Push-to-talk on"
            ],
            [
                "ptt_off",
                "Push-to-talk off"
            ]
        ]
    },
    {
        "label": "Notifications",
        "events": [
            [
                "mention",
                "Mention"
            ],
            [
                "keyword",
                "Keyword highlight"
            ],
            [
                "dm",
                "Direct message"
            ],
            [
                "channel_message",
                "Channel message"
            ],
            [
                "whisper",
                "Voice whisper"
            ],
            [
                "poke",
                "Poke"
            ],
            [
                "join_leave",
                "Join/leave (your channel)"
            ],
            [
                "buddy_online",
                "Watched contact online"
            ],
            [
                "kick",
                "Kick/ban"
            ],
            [
                "ban",
                "Banned"
            ],
            [
                "ban",
                "Banned"
            ],
            [
                "announcement",
                "Announcement"
            ],
            [
                "channel_watch",
                "Channel watch"
            ]
        ]
    }
];
