// Generated by tools/generate-speech.py. Static assets only.
export const SPEECH_ASSETS = {
    en: {
        banned: { url: new URL("./assets/speech/en/banned.wav", import.meta.url).href, duration: 1.5441269841269842 },
        kicked: { url: new URL("./assets/speech/en/kicked.wav", import.meta.url).href, duration: 1.3815873015873017 },
        kicked_channel: { url: new URL("./assets/speech/en/kicked_channel.wav", import.meta.url).href, duration: 1.555736961451247 },
        connection_lost: { url: new URL("./assets/speech/en/connection_lost.wav", import.meta.url).href, duration: 2.2175056689342405 },
        reconnect_failed: { url: new URL("./assets/speech/en/reconnect_failed.wav", import.meta.url).href, duration: 2.078185941043084 },
        permission_denied: { url: new URL("./assets/speech/en/permission_denied.wav", import.meta.url).href, duration: 2.4729251700680273 },
        moved_by_admin: { url: new URL("./assets/speech/en/moved_by_admin.wav", import.meta.url).href, duration: 1.811156462585034 },
        server_shutdown: { url: new URL("./assets/speech/en/server_shutdown.wav", import.meta.url).href, duration: 1.8575963718820863 },
        test: { url: new URL("./assets/speech/en/test.wav", import.meta.url).href, duration: 2.716734693877551 },
    },
    de: {
        banned: { url: new URL("./assets/speech/de/banned.wav", import.meta.url).href, duration: 1.3216326530612246 },
        kicked: { url: new URL("./assets/speech/de/kicked.wav", import.meta.url).href, duration: 1.566077097505669 },
        kicked_channel: { url: new URL("./assets/speech/de/kicked_channel.wav", import.meta.url).href, duration: 1.7719727891156463 },
        connection_lost: { url: new URL("./assets/speech/de/connection_lost.wav", import.meta.url).href, duration: 2.0932879818594103 },
        reconnect_failed: { url: new URL("./assets/speech/de/reconnect_failed.wav", import.meta.url).href, duration: 2.7843537414965986 },
        permission_denied: { url: new URL("./assets/speech/de/permission_denied.wav", import.meta.url).href, duration: 2.046031746031746 },
        moved_by_admin: { url: new URL("./assets/speech/de/moved_by_admin.wav", import.meta.url).href, duration: 1.987845804988662 },
        server_shutdown: { url: new URL("./assets/speech/de/server_shutdown.wav", import.meta.url).href, duration: 1.4982312925170067 },
        test: { url: new URL("./assets/speech/de/test.wav", import.meta.url).href, duration: 2.612426303854875 },
    },
};
