// Generated by tools/generate-speech.py. Static assets only.
export const SPEECH_ASSETS = {
    en: {
        banned: { url: new URL("./assets/speech/en/banned.wav", import.meta.url).href, duration: 1.6718367346938776, transcript: "You were banned from the server." },
        kicked: { url: new URL("./assets/speech/en/kicked.wav", import.meta.url).href, duration: 1.5441269841269842, transcript: "You were kicked from the server." },
        kicked_channel: { url: new URL("./assets/speech/en/kicked_channel.wav", import.meta.url).href, duration: 1.555736961451247, transcript: "You were removed from the channel." },
        connection_lost: { url: new URL("./assets/speech/en/connection_lost.wav", import.meta.url).href, duration: 2.2175056689342405, transcript: "Connection to the server was lost." },
        reconnect_failed: { url: new URL("./assets/speech/en/reconnect_failed.wav", import.meta.url).href, duration: 2.414875283446712, transcript: "Unable to reconnect to the server." },
        permission_denied: { url: new URL("./assets/speech/en/permission_denied.wav", import.meta.url).href, duration: 2.8560544217687074, transcript: "You do not have permission to perform this action." },
        moved_by_admin: { url: new URL("./assets/speech/en/moved_by_admin.wav", import.meta.url).href, duration: 1.8575963718820863, transcript: "You were moved to another channel." },
        server_shutdown: { url: new URL("./assets/speech/en/server_shutdown.wav", import.meta.url).href, duration: 1.8924263038548752, transcript: "The server is shutting down." },
        test: { url: new URL("./assets/speech/en/test.wav", import.meta.url).href, duration: 2.4961451247165534, transcript: "This is a noXa spoken notification." },
    },
    de: {
        banned: { url: new URL("./assets/speech/de/banned.wav", import.meta.url).href, duration: 1.397687074829932, transcript: "Du wurdest vom Server gebannt." },
        kicked: { url: new URL("./assets/speech/de/kicked.wav", import.meta.url).href, duration: 1.6166893424036282, transcript: "Du wurdest vom Server entfernt." },
        kicked_channel: { url: new URL("./assets/speech/de/kicked_channel.wav", import.meta.url).href, duration: 1.7229024943310658, transcript: "Du wurdest aus dem Channel entfernt." },
        connection_lost: { url: new URL("./assets/speech/de/connection_lost.wav", import.meta.url).href, duration: 2.074784580498866, transcript: "Die Verbindung zum Server wurde unterbrochen." },
        reconnect_failed: { url: new URL("./assets/speech/de/reconnect_failed.wav", import.meta.url).href, duration: 2.911201814058957, transcript: "Die Verbindung zum Server konnte nicht wiederhergestellt werden." },
        permission_denied: { url: new URL("./assets/speech/de/permission_denied.wav", import.meta.url).href, duration: 2.0742403628117914, transcript: "Du hast keine Berechtigung für diese Aktion." },
        moved_by_admin: { url: new URL("./assets/speech/de/moved_by_admin.wav", import.meta.url).href, duration: 2.1452154195011337, transcript: "Du wurdest in einen anderen Channel verschoben." },
        server_shutdown: { url: new URL("./assets/speech/de/server_shutdown.wav", import.meta.url).href, duration: 1.6096598639455781, transcript: "Der Server wird heruntergefahren." },
        test: { url: new URL("./assets/speech/de/test.wav", import.meta.url).href, duration: 2.5004988662131518, transcript: "Dies ist eine gesprochene noXa-Benachrichtigung." },
    },
};
