version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      codeql:
        patterns:
          - "github/codeql-action/*"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/client"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/client/frontend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/client/third_party/go-webview2"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
