// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptServerRules(arg1) {
  return window['go']['main']['App']['AcceptServerRules'](arg1);
}

export function AcceptServerRulesForTab(arg1, arg2) {
  return window['go']['main']['App']['AcceptServerRulesForTab'](arg1, arg2);
}

export function ApplyAndRestart() {
  return window['go']['main']['App']['ApplyAndRestart']();
}

export function ApplyHotkeyProfile(arg1) {
  return window['go']['main']['App']['ApplyHotkeyProfile'](arg1);
}

export function AuditLog(arg1, arg2) {
  return window['go']['main']['App']['AuditLog'](arg1, arg2);
}

export function AuditLogForTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['AuditLogForTab'](arg1, arg2, arg3);
}

export function BanList() {
  return window['go']['main']['App']['BanList']();
}

export function BanListForTab(arg1) {
  return window['go']['main']['App']['BanListForTab'](arg1);
}

export function CancelTransfer(arg1) {
  return window['go']['main']['App']['CancelTransfer'](arg1);
}

export function CancelTransferForTab(arg1, arg2) {
  return window['go']['main']['App']['CancelTransferForTab'](arg1, arg2);
}

export function CertificateClockWarning() {
  return window['go']['main']['App']['CertificateClockWarning']();
}

export function ChangeRoleChannel(arg1) {
  return window['go']['main']['App']['ChangeRoleChannel'](arg1);
}

export function ChangeRoleChannelForTab(arg1, arg2) {
  return window['go']['main']['App']['ChangeRoleChannelForTab'](arg1, arg2);
}

export function ChannelIconGet(arg1) {
  return window['go']['main']['App']['ChannelIconGet'](arg1);
}

export function ChannelIconGetForTab(arg1, arg2) {
  return window['go']['main']['App']['ChannelIconGetForTab'](arg1, arg2);
}

export function ChannelIconSet(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChannelIconSet'](arg1, arg2, arg3);
}

export function ChannelIconSetForTab(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ChannelIconSetForTab'](arg1, arg2, arg3, arg4);
}

export function ChatDeleteMessage(arg1) {
  return window['go']['main']['App']['ChatDeleteMessage'](arg1);
}

export function ChatDeleteMessageForTab(arg1, arg2) {
  return window['go']['main']['App']['ChatDeleteMessageForTab'](arg1, arg2);
}

export function ChatEditMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ChatEditMessage'](arg1, arg2, arg3, arg4);
}

export function ChatEditMessageForTab(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ChatEditMessageForTab'](arg1, arg2, arg3, arg4, arg5);
}

export function ChatExportHistory(arg1, arg2) {
  return window['go']['main']['App']['ChatExportHistory'](arg1, arg2);
}

export function ChatExportHistoryForTab(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ChatExportHistoryForTab'](arg1, arg2, arg3, arg4);
}

export function ChatFilterGet() {
  return window['go']['main']['App']['ChatFilterGet']();
}

export function ChatFilterGetForTab(arg1) {
  return window['go']['main']['App']['ChatFilterGetForTab'](arg1);
}

export function ChatFilterSet(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChatFilterSet'](arg1, arg2, arg3);
}

export function ChatFilterSetForTab(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ChatFilterSetForTab'](arg1, arg2, arg3, arg4);
}

export function ChatHistory(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChatHistory'](arg1, arg2, arg3);
}

export function ChatHistoryForTab(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ChatHistoryForTab'](arg1, arg2, arg3, arg4);
}

export function ChatPinMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChatPinMessage'](arg1, arg2, arg3);
}

export function ChatPinMessageForTab(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ChatPinMessageForTab'](arg1, arg2, arg3, arg4);
}

export function ChatPins(arg1) {
  return window['go']['main']['App']['ChatPins'](arg1);
}

export function ChatPinsForTab(arg1, arg2) {
  return window['go']['main']['App']['ChatPinsForTab'](arg1, arg2);
}

export function ChatReact(arg1, arg2) {
  return window['go']['main']['App']['ChatReact'](arg1, arg2);
}

export function ChatReactForTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChatReactForTab'](arg1, arg2, arg3);
}

export function ChatSearch(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChatSearch'](arg1, arg2, arg3);
}

export function ChatSearchForTab(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ChatSearchForTab'](arg1, arg2, arg3, arg4, arg5);
}

export function CheckAccess(arg1) {
  return window['go']['main']['App']['CheckAccess'](arg1);
}

export function CheckAccessForTab(arg1, arg2) {
  return window['go']['main']['App']['CheckAccessForTab'](arg1, arg2);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ClientID() {
  return window['go']['main']['App']['ClientID']();
}

export function ClientVersion() {
  return window['go']['main']['App']['ClientVersion']();
}

export function ClientVersionShort() {
  return window['go']['main']['App']['ClientVersionShort']();
}

export function CloseTab(arg1) {
  return window['go']['main']['App']['CloseTab'](arg1);
}

export function ComplaintClear(arg1, arg2) {
  return window['go']['main']['App']['ComplaintClear'](arg1, arg2);
}

export function ComplaintClearForTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['ComplaintClearForTab'](arg1, arg2, arg3);
}

export function ComplaintList() {
  return window['go']['main']['App']['ComplaintList']();
}

export function ComplaintListForTab(arg1) {
  return window['go']['main']['App']['ComplaintListForTab'](arg1);
}

export function Connect(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3, arg4);
}

export function ConnectBookmarkTab(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ConnectBookmarkTab'](arg1, arg2, arg3, arg4, arg5);
}

export function ConnectBookmarkTabWithID(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ConnectBookmarkTabWithID'](arg1, arg2, arg3, arg4, arg5);
}

export function ConnectGuest(arg1, arg2) {
  return window['go']['main']['App']['ConnectGuest'](arg1, arg2);
}

export function ConnectGuestBookmarkTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConnectGuestBookmarkTab'](arg1, arg2, arg3);
}

export function ConnectGuestBookmarkTabWithID(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConnectGuestBookmarkTabWithID'](arg1, arg2, arg3);
}

export function ConnectGuestTab(arg1, arg2) {
  return window['go']['main']['App']['ConnectGuestTab'](arg1, arg2);
}

export function ConnectTab(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ConnectTab'](arg1, arg2, arg3, arg4);
}

export function Connected() {
  return window['go']['main']['App']['Connected']();
}

export function ConnectionSecurity() {
  return window['go']['main']['App']['ConnectionSecurity']();
}

export function ConversationForTab(arg1, arg2) {
  return window['go']['main']['App']['ConversationForTab'](arg1, arg2);
}

export function CreateIdentity(arg1) {
  return window['go']['main']['App']['CreateIdentity'](arg1);
}

export function CreatePollForTab(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreatePollForTab'](arg1, arg2, arg3, arg4);
}

export function DMExportHistory(arg1) {
  return window['go']['main']['App']['DMExportHistory'](arg1);
}

export function DMExportHistoryForContext(arg1, arg2) {
  return window['go']['main']['App']['DMExportHistoryForContext'](arg1, arg2);
}

export function DMHistoryAppend(arg1, arg2, arg3) {
  return window['go']['main']['App']['DMHistoryAppend'](arg1, arg2, arg3);
}

export function DMHistoryAppendForContext(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DMHistoryAppendForContext'](arg1, arg2, arg3, arg4);
}

export function DMHistoryClear(arg1) {
  return window['go']['main']['App']['DMHistoryClear'](arg1);
}

export function DMHistoryClearForContext(arg1, arg2) {
  return window['go']['main']['App']['DMHistoryClearForContext'](arg1, arg2);
}

export function DMHistoryContextForTab(arg1) {
  return window['go']['main']['App']['DMHistoryContextForTab'](arg1);
}

export function DMHistoryLoad(arg1) {
  return window['go']['main']['App']['DMHistoryLoad'](arg1);
}

export function DMHistoryLoadForContext(arg1, arg2) {
  return window['go']['main']['App']['DMHistoryLoadForContext'](arg1, arg2);
}

export function DMHistoryPeers() {
  return window['go']['main']['App']['DMHistoryPeers']();
}

export function DMHistoryPeersForContext(arg1) {
  return window['go']['main']['App']['DMHistoryPeersForContext'](arg1);
}

export function DMSearch(arg1, arg2, arg3) {
  return window['go']['main']['App']['DMSearch'](arg1, arg2, arg3);
}

export function DMSearchForContext(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DMSearchForContext'](arg1, arg2, arg3, arg4);
}

export function DeleteIdentity(arg1, arg2) {
  return window['go']['main']['App']['DeleteIdentity'](arg1, arg2);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function DisconnectMemberForTab(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DisconnectMemberForTab'](arg1, arg2, arg3, arg4);
}

export function DisconnectTab(arg1) {
  return window['go']['main']['App']['DisconnectTab'](arg1);
}

export function DownloadAndApply(arg1) {
  return window['go']['main']['App']['DownloadAndApply'](arg1);
}

export function DownloadChatAttachment(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadChatAttachment'](arg1, arg2, arg3);
}

export function DownloadChatAttachmentForTab(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DownloadChatAttachmentForTab'](arg1, arg2, arg3, arg4);
}

export function DownloadFile(arg1, arg2) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2);
}

export function DownloadFileProgress(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['DownloadFileProgress'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DownloadFileProgressForTab(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['DownloadFileProgressForTab'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function DownloadPath(arg1) {
  return window['go']['main']['App']['DownloadPath'](arg1);
}

export function E2EEDiagnostics(arg1) {
  return window['go']['main']['App']['E2EEDiagnostics'](arg1);
}

export function EmojiDelete(arg1) {
  return window['go']['main']['App']['EmojiDelete'](arg1);
}

export function EmojiDeleteForTab(arg1, arg2) {
  return window['go']['main']['App']['EmojiDeleteForTab'](arg1, arg2);
}

export function EmojiGet(arg1) {
  return window['go']['main']['App']['EmojiGet'](arg1);
}

export function EmojiGetForTab(arg1, arg2) {
  return window['go']['main']['App']['EmojiGetForTab'](arg1, arg2);
}

export function EmojiList() {
  return window['go']['main']['App']['EmojiList']();
}

export function EmojiListForTab(arg1) {
  return window['go']['main']['App']['EmojiListForTab'](arg1);
}

export function EmojiRename(arg1, arg2) {
  return window['go']['main']['App']['EmojiRename'](arg1, arg2);
}

export function EmojiRenameForTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['EmojiRenameForTab'](arg1, arg2, arg3);
}

export function EmojiUpload(arg1, arg2) {
  return window['go']['main']['App']['EmojiUpload'](arg1, arg2);
}

export function EmojiUploadForTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['EmojiUploadForTab'](arg1, arg2, arg3);
}

export function ExportChat(arg1, arg2) {
  return window['go']['main']['App']['ExportChat'](arg1, arg2);
}

export function ExportChatEncrypted(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportChatEncrypted'](arg1, arg2, arg3);
}

export function ExportIdentity(arg1) {
  return window['go']['main']['App']['ExportIdentity'](arg1);
}

export function ExportLogs() {
  return window['go']['main']['App']['ExportLogs']();
}

export function FileDelete(arg1, arg2, arg3) {
  return window['go']['main']['App']['FileDelete'](arg1, arg2, arg3);
}

export function FileDeleteForTab(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['FileDeleteForTab'](arg1, arg2, arg3, arg4);
}

export function FileLink(arg1, arg2, arg3) {
  return window['go']['main']['App']['FileLink'](arg1, arg2, arg3);
}

export function FileLinkForTab(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['FileLinkForTab'](arg1, arg2, arg3, arg4);
}

export function FileList(arg1, arg2) {
  return window['go']['main']['App']['FileList'](arg1, arg2);
}

export function FileListForTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['FileListForTab'](arg1, arg2, arg3);
}

export function FileRename(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['FileRename'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function FileRenameForTab(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['FileRenameForTab'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function FileVersions(arg1, arg2, arg3) {
  return window['go']['main']['App']['FileVersions'](arg1, arg2, arg3);
}

export function FileVersionsForTab(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['FileVersionsForTab'](arg1, arg2, arg3, arg4);
}

export function FlashWindow() {
  return window['go']['main']['App']['FlashWindow']();
}

export function GetAvatar(arg1) {
  return window['go']['main']['App']['GetAvatar'](arg1);
}

export function GetAvatarForTab(arg1, arg2) {
  return window['go']['main']['App']['GetAvatarForTab'](arg1, arg2);
}

export function GetClientInfo(arg1) {
  return window['go']['main']['App']['GetClientInfo'](arg1);
}

export function GetClientInfoForTab(arg1, arg2) {
  return window['go']['main']['App']['GetClientInfoForTab'](arg1, arg2);
}

export function GetICEServers() {
  return window['go']['main']['App']['GetICEServers']();
}

export function GetICEServersForTab(arg1) {
  return window['go']['main']['App']['GetICEServersForTab'](arg1);
}

export function GetMediaLimits() {
  return window['go']['main']['App']['GetMediaLimits']();
}

export function GetMediaLimitsForTab(arg1) {
  return window['go']['main']['App']['GetMediaLimitsForTab'](arg1);
}

export function GetServerConfig() {
  return window['go']['main']['App']['GetServerConfig']();
}

export function GetServerConfigForTab(arg1) {
  return window['go']['main']['App']['GetServerConfigForTab'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IdentityBackupPending() {
  return window['go']['main']['App']['IdentityBackupPending']();
}

export function IdentityInfo() {
  return window['go']['main']['App']['IdentityInfo']();
}

export function IdentityUID() {
  return window['go']['main']['App']['IdentityUID']();
}

export function ImportIdentity() {
  return window['go']['main']['App']['ImportIdentity']();
}

export function ImproveIdentityLevel(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImproveIdentityLevel'](arg1, arg2, arg3);
}

export function IsGuest() {
  return window['go']['main']['App']['IsGuest']();
}

export function JoinChannel(arg1) {
  return window['go']['main']['App']['JoinChannel'](arg1);
}

export function JoinChannelForTab(arg1, arg2) {
  return window['go']['main']['App']['JoinChannelForTab'](arg1, arg2);
}

export function KickClient(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['KickClient'](arg1, arg2, arg3, arg4, arg5);
}

export function KickClientForTab(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['KickClientForTab'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function LastCrash() {
  return window['go']['main']['App']['LastCrash']();
}

export function ListIdentities() {
  return window['go']['main']['App']['ListIdentities']();
}

export function ListTabs() {
  return window['go']['main']['App']['ListTabs']();
}

export function LogChat(arg1) {
  return window['go']['main']['App']['LogChat'](arg1);
}

export function MOTD() {
  return window['go']['main']['App']['MOTD']();
}

export function MOTDForTab(arg1) {
  return window['go']['main']['App']['MOTDForTab'](arg1);
}

export function MoveClient(arg1, arg2) {
  return window['go']['main']['App']['MoveClient'](arg1, arg2);
}

export function MoveClientForTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveClientForTab'](arg1, arg2, arg3);
}

export function Notify(arg1, arg2) {
  return window['go']['main']['App']['Notify'](arg1, arg2);
}

export function OpenDownloadFolderForTab(arg1, arg2) {
  return window['go']['main']['App']['OpenDownloadFolderForTab'](arg1, arg2);
}

export function OpenLogFolder() {
  return window['go']['main']['App']['OpenLogFolder']();
}

export function OpenPrivateCallDescriptionForTab(arg1, arg2) {
  return window['go']['main']['App']['OpenPrivateCallDescriptionForTab'](arg1, arg2);
}

export function PickDownloadFolder() {
  return window['go']['main']['App']['PickDownloadFolder']();
}

export function PickSavePath(arg1) {
  return window['go']['main']['App']['PickSavePath'](arg1);
}

export function PickUploadPaths() {
  return window['go']['main']['App']['PickUploadPaths']();
}

export function Poke(arg1, arg2) {
  return window['go']['main']['App']['Poke'](arg1, arg2);
}

export function PokeForTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['PokeForTab'](arg1, arg2, arg3);
}

export function PollForTab(arg1, arg2) {
  return window['go']['main']['App']['PollForTab'](arg1, arg2);
}

export function PositionalInputPath() {
  return window['go']['main']['App']['PositionalInputPath']();
}

export function PreviewChannelAccessForTab(arg1, arg2) {
  return window['go']['main']['App']['PreviewChannelAccessForTab'](arg1, arg2);
}

export function PrivateCallForTab(arg1, arg2) {
  return window['go']['main']['App']['PrivateCallForTab'](arg1, arg2);
}

export function PublishPositionForTab(arg1, arg2) {
  return window['go']['main']['App']['PublishPositionForTab'](arg1, arg2);
}

export function ReadPositionalInput() {
  return window['go']['main']['App']['ReadPositionalInput']();
}

export function RecordRecent(arg1, arg2) {
  return window['go']['main']['App']['RecordRecent'](arg1, arg2);
}

export function RegenerateIdentity() {
  return window['go']['main']['App']['RegenerateIdentity']();
}

export function RemoveRoleBanForTab(arg1, arg2) {
  return window['go']['main']['App']['RemoveRoleBanForTab'](arg1, arg2);
}

export function RenameIdentity(arg1, arg2) {
  return window['go']['main']['App']['RenameIdentity'](arg1, arg2);
}

export function RoleChange(arg1) {
  return window['go']['main']['App']['RoleChange'](arg1);
}

export function RoleChangeForTab(arg1, arg2) {
  return window['go']['main']['App']['RoleChangeForTab'](arg1, arg2);
}

export function RoleChannelState(arg1) {
  return window['go']['main']['App']['RoleChannelState'](arg1);
}

export function RoleChannelStateForTab(arg1, arg2) {
  return window['go']['main']['App']['RoleChannelStateForTab'](arg1, arg2);
}

export function RoleMembers(arg1) {
  return window['go']['main']['App']['RoleMembers'](arg1);
}

export function RoleMembersForTab(arg1, arg2) {
  return window['go']['main']['App']['RoleMembersForTab'](arg1, arg2);
}

export function RoleState(arg1) {
  return window['go']['main']['App']['RoleState'](arg1);
}

export function RoleStateForTab(arg1, arg2) {
  return window['go']['main']['App']['RoleStateForTab'](arg1, arg2);
}

export function SaveChatAttachment(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveChatAttachment'](arg1, arg2, arg3, arg4);
}

export function SaveChatAttachmentForTab(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveChatAttachmentForTab'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SendChat(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendChat'](arg1, arg2, arg3);
}

export function SendChatDelivered(arg1, arg2) {
  return window['go']['main']['App']['SendChatDelivered'](arg1, arg2);
}

export function SendChatDeliveredForTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendChatDeliveredForTab'](arg1, arg2, arg3);
}

export function SendChatForTab(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendChatForTab'](arg1, arg2, arg3, arg4);
}

export function SendChatRead(arg1, arg2) {
  return window['go']['main']['App']['SendChatRead'](arg1, arg2);
}

export function SendChatReadForTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendChatReadForTab'](arg1, arg2, arg3);
}

export function SendChatReply(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendChatReply'](arg1, arg2, arg3, arg4);
}

export function SendChatReplyForTab(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SendChatReplyForTab'](arg1, arg2, arg3, arg4, arg5);
}

export function SendConversationForTab(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendConversationForTab'](arg1, arg2, arg3, arg4);
}

export function SendICECandidate(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendICECandidate'](arg1, arg2, arg3);
}

export function SendICECandidateForTab(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendICECandidateForTab'](arg1, arg2, arg3, arg4);
}

export function SendPrivateCallDescriptionForTab(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SendPrivateCallDescriptionForTab'](arg1, arg2, arg3, arg4, arg5);
}

export function SendTyping(arg1, arg2) {
  return window['go']['main']['App']['SendTyping'](arg1, arg2);
}

export function SendTypingForTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendTypingForTab'](arg1, arg2, arg3);
}

export function ServerBannerGet() {
  return window['go']['main']['App']['ServerBannerGet']();
}

export function ServerBannerGetForTab(arg1) {
  return window['go']['main']['App']['ServerBannerGetForTab'](arg1);
}

export function ServerBannerSet(arg1) {
  return window['go']['main']['App']['ServerBannerSet'](arg1);
}

export function ServerBannerSetForTab(arg1, arg2) {
  return window['go']['main']['App']['ServerBannerSetForTab'](arg1, arg2);
}

export function ServerFingerprint() {
  return window['go']['main']['App']['ServerFingerprint']();
}

export function ServerIconGet() {
  return window['go']['main']['App']['ServerIconGet']();
}

export function ServerIconGetForTab(arg1) {
  return window['go']['main']['App']['ServerIconGetForTab'](arg1);
}

export function ServerIconSet(arg1) {
  return window['go']['main']['App']['ServerIconSet'](arg1);
}

export function ServerIconSetForTab(arg1, arg2) {
  return window['go']['main']['App']['ServerIconSetForTab'](arg1, arg2);
}

export function ServerInfo() {
  return window['go']['main']['App']['ServerInfo']();
}

export function ServerInfoForTab(arg1) {
  return window['go']['main']['App']['ServerInfoForTab'](arg1);
}

export function SessionInfoForTab(arg1) {
  return window['go']['main']['App']['SessionInfoForTab'](arg1);
}

export function SetActiveTab(arg1) {
  return window['go']['main']['App']['SetActiveTab'](arg1);
}

export function SetAlwaysOnTop(arg1) {
  return window['go']['main']['App']['SetAlwaysOnTop'](arg1);
}

export function SetAvatar(arg1) {
  return window['go']['main']['App']['SetAvatar'](arg1);
}

export function SetAvatarForTab(arg1, arg2) {
  return window['go']['main']['App']['SetAvatarForTab'](arg1, arg2);
}

export function SetDebugFrames(arg1) {
  return window['go']['main']['App']['SetDebugFrames'](arg1);
}

export function SetHotkey(arg1, arg2) {
  return window['go']['main']['App']['SetHotkey'](arg1, arg2);
}

export function SetHotkeys(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetHotkeys'](arg1, arg2, arg3);
}

export function SetMediaLimitsForTab(arg1, arg2) {
  return window['go']['main']['App']['SetMediaLimitsForTab'](arg1, arg2);
}

export function SetMemberVoice(arg1) {
  return window['go']['main']['App']['SetMemberVoice'](arg1);
}

export function SetMemberVoiceForTab(arg1, arg2) {
  return window['go']['main']['App']['SetMemberVoiceForTab'](arg1, arg2);
}

export function SetMuted(arg1) {
  return window['go']['main']['App']['SetMuted'](arg1);
}

export function SetPTT(arg1) {
  return window['go']['main']['App']['SetPTT'](arg1);
}

export function SetPrioritySpeaker(arg1) {
  return window['go']['main']['App']['SetPrioritySpeaker'](arg1);
}

export function SetPrioritySpeakerForTab(arg1, arg2) {
  return window['go']['main']['App']['SetPrioritySpeakerForTab'](arg1, arg2);
}

export function SetRoleChannelIconForTab(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetRoleChannelIconForTab'](arg1, arg2, arg3, arg4);
}

export function SetScreenShare(arg1) {
  return window['go']['main']['App']['SetScreenShare'](arg1);
}

export function SetScreenShareForTab(arg1, arg2) {
  return window['go']['main']['App']['SetScreenShareForTab'](arg1, arg2);
}

export function SetScreenShareQuality(arg1, arg2) {
  return window['go']['main']['App']['SetScreenShareQuality'](arg1, arg2);
}

export function SetScreenShareQualityForTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetScreenShareQualityForTab'](arg1, arg2, arg3);
}

export function SetServerConfig(arg1) {
  return window['go']['main']['App']['SetServerConfig'](arg1);
}

export function SetServerConfigForTab(arg1, arg2) {
  return window['go']['main']['App']['SetServerConfigForTab'](arg1, arg2);
}

export function SetStatus(arg1, arg2) {
  return window['go']['main']['App']['SetStatus'](arg1, arg2);
}

export function SetStatusForTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetStatusForTab'](arg1, arg2, arg3);
}

export function SetTrayVoiceState(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetTrayVoiceState'](arg1, arg2, arg3);
}

export function SetVideoQuality(arg1) {
  return window['go']['main']['App']['SetVideoQuality'](arg1);
}

export function SetVideoQualityForTab(arg1, arg2) {
  return window['go']['main']['App']['SetVideoQualityForTab'](arg1, arg2);
}

export function SetWindowOpacity(arg1) {
  return window['go']['main']['App']['SetWindowOpacity'](arg1);
}

export function StopPrivateCallForTab(arg1, arg2) {
  return window['go']['main']['App']['StopPrivateCallForTab'](arg1, arg2);
}

export function SubscribeChannels(arg1, arg2) {
  return window['go']['main']['App']['SubscribeChannels'](arg1, arg2);
}

export function SubscribeChannelsForTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['SubscribeChannelsForTab'](arg1, arg2, arg3);
}

export function Subscriptions() {
  return window['go']['main']['App']['Subscriptions']();
}

export function SubscriptionsForTab(arg1) {
  return window['go']['main']['App']['SubscriptionsForTab'](arg1);
}

export function SwitchIdentity(arg1) {
  return window['go']['main']['App']['SwitchIdentity'](arg1);
}

export function SystemCPUPercent() {
  return window['go']['main']['App']['SystemCPUPercent']();
}

export function TrayClearMentions() {
  return window['go']['main']['App']['TrayClearMentions']();
}

export function TrayMention() {
  return window['go']['main']['App']['TrayMention']();
}

export function TrustServerFingerprint(arg1, arg2) {
  return window['go']['main']['App']['TrustServerFingerprint'](arg1, arg2);
}

export function UploadChatAttachment(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadChatAttachment'](arg1, arg2, arg3);
}

export function UploadChatAttachmentForTab(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UploadChatAttachmentForTab'](arg1, arg2, arg3, arg4);
}

export function UploadFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2, arg3);
}

export function UploadFileProgress(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UploadFileProgress'](arg1, arg2, arg3, arg4, arg5);
}

export function UploadFileProgressForTab(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UploadFileProgressForTab'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UploadPathProgress(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UploadPathProgress'](arg1, arg2, arg3, arg4);
}

export function UploadPathProgressForTab(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UploadPathProgressForTab'](arg1, arg2, arg3, arg4, arg5);
}

export function VerifyFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['VerifyFile'](arg1, arg2, arg3, arg4);
}

export function VerifyFileForTab(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['VerifyFileForTab'](arg1, arg2, arg3, arg4, arg5);
}

export function VideoStreamControlForTab(arg1, arg2) {
  return window['go']['main']['App']['VideoStreamControlForTab'](arg1, arg2);
}

export function WebRTCAnswer(arg1) {
  return window['go']['main']['App']['WebRTCAnswer'](arg1);
}

export function WebRTCAnswerForTab(arg1, arg2) {
  return window['go']['main']['App']['WebRTCAnswerForTab'](arg1, arg2);
}

export function WebRTCOffer(arg1, arg2) {
  return window['go']['main']['App']['WebRTCOffer'](arg1, arg2);
}

export function WebRTCOfferForTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['WebRTCOfferForTab'](arg1, arg2, arg3);
}

export function WhatsNew() {
  return window['go']['main']['App']['WhatsNew']();
}

export function WhisperSet(arg1, arg2, arg3) {
  return window['go']['main']['App']['WhisperSet'](arg1, arg2, arg3);
}

export function WhisperSetForTab(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['WhisperSetForTab'](arg1, arg2, arg3, arg4);
}
