// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {netproto} from '../models';
import {main} from '../models';
import {authorization} from '../models';

export function AcceptServerRules(arg1:string):Promise<string>;

export function AcceptServerRulesForTab(arg1:string,arg2:string):Promise<string>;

export function ApplyAndRestart():Promise<string>;

export function ApplyHotkeyProfile(arg1:string):Promise<void>;

export function AuditLog(arg1:number,arg2:number):Promise<netproto.AuditLogResponse>;

export function AuditLogForTab(arg1:string,arg2:number,arg3:number):Promise<netproto.AuditLogResponse>;

export function BanList():Promise<netproto.BanListResponse>;

export function BanListForTab(arg1:string):Promise<netproto.BanListResponse>;

export function CancelTransfer(arg1:string):Promise<void>;

export function CancelTransferForTab(arg1:string,arg2:string):Promise<string>;

export function CertificateClockWarning():Promise<string>;

export function ChangeRoleChannel(arg1:netproto.RoleChannelChange):Promise<netproto.RoleChannelResult>;

export function ChangeRoleChannelForTab(arg1:string,arg2:netproto.RoleChannelChange):Promise<netproto.RoleChannelResult>;

export function ChannelIconGet(arg1:number):Promise<netproto.ChannelIconData>;

export function ChannelIconGetForTab(arg1:string,arg2:number):Promise<netproto.ChannelIconData>;

export function ChannelIconSet(arg1:number,arg2:string,arg3:number):Promise<string>;

export function ChannelIconSetForTab(arg1:string,arg2:number,arg3:string,arg4:number):Promise<string>;

export function ChatDeleteMessage(arg1:number):Promise<string>;

export function ChatDeleteMessageForTab(arg1:string,arg2:number):Promise<string>;

export function ChatEditMessage(arg1:number,arg2:number,arg3:string,arg4:number):Promise<string>;

export function ChatEditMessageForTab(arg1:string,arg2:number,arg3:number,arg4:string,arg5:number):Promise<string>;

export function ChatExportHistory(arg1:number,arg2:number):Promise<main.ChatExportResult>;

export function ChatExportHistoryForTab(arg1:string,arg2:string,arg3:number,arg4:number):Promise<main.ChatExportResult>;

export function ChatFilterGet():Promise<netproto.ChatFilterResponse>;

export function ChatFilterGetForTab(arg1:string):Promise<netproto.ChatFilterResponse>;

export function ChatFilterSet(arg1:string,arg2:string,arg3:string):Promise<netproto.ChatFilterResponse>;

export function ChatFilterSetForTab(arg1:string,arg2:string,arg3:string,arg4:string):Promise<netproto.ChatFilterResponse>;

export function ChatHistory(arg1:number,arg2:number,arg3:number):Promise<netproto.ChatHistoryResponse>;

export function ChatHistoryForTab(arg1:string,arg2:number,arg3:number,arg4:number):Promise<netproto.ChatHistoryResponse>;

export function ChatPinMessage(arg1:number,arg2:number,arg3:boolean):Promise<string>;

export function ChatPinMessageForTab(arg1:string,arg2:number,arg3:number,arg4:boolean):Promise<string>;

export function ChatPins(arg1:number):Promise<netproto.ChatPinsResponse>;

export function ChatPinsForTab(arg1:string,arg2:number):Promise<netproto.ChatPinsResponse>;

export function ChatReact(arg1:number,arg2:string):Promise<string>;

export function ChatReactForTab(arg1:string,arg2:number,arg3:string):Promise<string>;

export function ChatSearch(arg1:number,arg2:string,arg3:number):Promise<main.ChatSearchResult>;

export function ChatSearchForTab(arg1:string,arg2:string,arg3:number,arg4:string,arg5:number):Promise<main.ChatSearchResult>;

export function CheckAccess(arg1:netproto.AccessCheck):Promise<netproto.AccessCheckResult>;

export function CheckAccessForTab(arg1:string,arg2:netproto.AccessCheck):Promise<netproto.AccessCheckResult>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function ClientID():Promise<string>;

export function ClientVersion():Promise<string>;

export function ClientVersionShort():Promise<string>;

export function CloseTab(arg1:string):Promise<void>;

export function ComplaintClear(arg1:string,arg2:string):Promise<netproto.Complaints>;

export function ComplaintClearForTab(arg1:string,arg2:string,arg3:string):Promise<netproto.Complaints>;

export function ComplaintList():Promise<netproto.Complaints>;

export function ComplaintListForTab(arg1:string):Promise<netproto.Complaints>;

export function Connect(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function ConnectBookmarkTab(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function ConnectBookmarkTabWithID(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.ConnectTabResult>;

export function ConnectGuest(arg1:string,arg2:string):Promise<string>;

export function ConnectGuestBookmarkTab(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ConnectGuestBookmarkTabWithID(arg1:string,arg2:string,arg3:string):Promise<main.ConnectTabResult>;

export function ConnectGuestTab(arg1:string,arg2:string):Promise<string>;

export function ConnectTab(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function Connected():Promise<boolean>;

export function ConnectionSecurity():Promise<string>;

export function ConversationForTab(arg1:string,arg2:netproto.ConversationRequest):Promise<netproto.ConversationResult>;

export function CreateIdentity(arg1:string):Promise<string>;

export function CreatePollForTab(arg1:string,arg2:string,arg3:string,arg4:netproto.PollDefinition):Promise<string>;

export function DMExportHistory(arg1:string):Promise<main.ChatExportResult>;

export function DMExportHistoryForContext(arg1:main.DMHistoryContext,arg2:string):Promise<main.ChatExportResult>;

export function DMHistoryAppend(arg1:string,arg2:string,arg3:main.DMEntry):Promise<string>;

export function DMHistoryAppendForContext(arg1:main.DMHistoryContext,arg2:string,arg3:string,arg4:main.DMEntry):Promise<string>;

export function DMHistoryClear(arg1:string):Promise<string>;

export function DMHistoryClearForContext(arg1:main.DMHistoryContext,arg2:string):Promise<string>;

export function DMHistoryContextForTab(arg1:string):Promise<main.DMHistoryContext>;

export function DMHistoryLoad(arg1:string):Promise<Array<main.DMEntry>>;

export function DMHistoryLoadForContext(arg1:main.DMHistoryContext,arg2:string):Promise<Array<main.DMEntry>>;

export function DMHistoryPeers():Promise<Array<main.DMPeer>>;

export function DMHistoryPeersForContext(arg1:main.DMHistoryContext):Promise<Array<main.DMPeer>>;

export function DMSearch(arg1:string,arg2:string,arg3:number):Promise<main.ChatSearchResult>;

export function DMSearchForContext(arg1:main.DMHistoryContext,arg2:string,arg3:string,arg4:number):Promise<main.ChatSearchResult>;

export function DeleteIdentity(arg1:string,arg2:boolean):Promise<string>;

export function Disconnect():Promise<void>;

export function DisconnectMemberForTab(arg1:string,arg2:string,arg3:number,arg4:string):Promise<string>;

export function DisconnectTab(arg1:string):Promise<void>;

export function DownloadAndApply(arg1:main.UpdateInfo):Promise<string>;

export function DownloadChatAttachment(arg1:number,arg2:string,arg3:string):Promise<string>;

export function DownloadChatAttachmentForTab(arg1:string,arg2:number,arg3:string,arg4:string):Promise<string>;

export function DownloadFile(arg1:number,arg2:string):Promise<string>;

export function DownloadFileProgress(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string,arg6:number):Promise<string>;

export function DownloadFileProgressForTab(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string,arg6:string,arg7:number):Promise<string>;

export function DownloadPath(arg1:string):Promise<string>;

export function E2EEDiagnostics(arg1:string):Promise<main.E2EEDiagnostics>;

export function EmojiDelete(arg1:string):Promise<string>;

export function EmojiDeleteForTab(arg1:string,arg2:string):Promise<string>;

export function EmojiGet(arg1:string):Promise<netproto.EmojiData>;

export function EmojiGetForTab(arg1:string,arg2:string):Promise<netproto.EmojiData>;

export function EmojiList():Promise<netproto.EmojiListResponse>;

export function EmojiListForTab(arg1:string):Promise<netproto.EmojiListResponse>;

export function EmojiRename(arg1:string,arg2:string):Promise<string>;

export function EmojiRenameForTab(arg1:string,arg2:string,arg3:string):Promise<string>;

export function EmojiUpload(arg1:string,arg2:string):Promise<string>;

export function EmojiUploadForTab(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ExportChat(arg1:string,arg2:string):Promise<string>;

export function ExportChatEncrypted(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ExportIdentity(arg1:string):Promise<string>;

export function ExportLogs():Promise<string>;

export function FileDelete(arg1:number,arg2:string,arg3:string):Promise<string>;

export function FileDeleteForTab(arg1:string,arg2:number,arg3:string,arg4:string):Promise<string>;

export function FileLink(arg1:number,arg2:string,arg3:string):Promise<netproto.FileLinkResponse>;

export function FileLinkForTab(arg1:string,arg2:number,arg3:string,arg4:string):Promise<netproto.FileLinkResponse>;

export function FileList(arg1:number,arg2:string):Promise<netproto.FileListResponse>;

export function FileListForTab(arg1:string,arg2:number,arg3:string):Promise<netproto.FileListResponse>;

export function FileRename(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number):Promise<string>;

export function FileRenameForTab(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string,arg6:string,arg7:number):Promise<string>;

export function FileVersions(arg1:number,arg2:string,arg3:string):Promise<netproto.FileVersionsResponse>;

export function FileVersionsForTab(arg1:string,arg2:number,arg3:string,arg4:string):Promise<netproto.FileVersionsResponse>;

export function FlashWindow():Promise<string>;

export function GetAvatar(arg1:string):Promise<netproto.AvatarData>;

export function GetAvatarForTab(arg1:string,arg2:string):Promise<netproto.AvatarData>;

export function GetClientInfo(arg1:string):Promise<netproto.ClientInfoResponse>;

export function GetClientInfoForTab(arg1:string,arg2:string):Promise<netproto.ClientInfoResponse>;

export function GetICEServers():Promise<Array<netproto.ICEServer>>;

export function GetICEServersForTab(arg1:string):Promise<Array<netproto.ICEServer>>;

export function GetMediaLimits():Promise<netproto.MediaLimits>;

export function GetMediaLimitsForTab(arg1:string):Promise<netproto.MediaLimits>;

export function GetServerConfig():Promise<netproto.ServerConfig>;

export function GetServerConfigForTab(arg1:string):Promise<netproto.ServerConfig>;

export function GetSettings():Promise<main.Settings>;

export function Greet(arg1:string):Promise<string>;

export function IdentityBackupPending():Promise<boolean>;

export function IdentityInfo():Promise<main.identityInfo>;

export function IdentityUID():Promise<string>;

export function ImportIdentity():Promise<string>;

export function ImproveIdentityLevel(arg1:string,arg2:number,arg3:number):Promise<main.IdentityLevelResult>;

export function IsGuest():Promise<boolean>;

export function JoinChannel(arg1:number):Promise<string>;

export function JoinChannelForTab(arg1:string,arg2:number):Promise<string>;

export function KickClient(arg1:string,arg2:boolean,arg3:boolean,arg4:string,arg5:number):Promise<string>;

export function KickClientForTab(arg1:string,arg2:string,arg3:boolean,arg4:boolean,arg5:string,arg6:number):Promise<string>;

export function LastCrash():Promise<string>;

export function ListIdentities():Promise<Array<main.IdentityEntry>>;

export function ListTabs():Promise<Array<main.TabInfo>>;

export function LogChat(arg1:string):Promise<void>;

export function MOTD():Promise<string>;

export function MOTDForTab(arg1:string):Promise<string>;

export function MoveClient(arg1:string,arg2:number):Promise<string>;

export function MoveClientForTab(arg1:string,arg2:string,arg3:number):Promise<string>;

export function Notify(arg1:string,arg2:string):Promise<string>;

export function OpenDownloadFolderForTab(arg1:string,arg2:string):Promise<string>;

export function OpenLogFolder():Promise<string>;

export function OpenPrivateCallDescriptionForTab(arg1:string,arg2:netproto.CallSignal):Promise<main.PrivateCallDescription>;

export function PickDownloadFolder():Promise<string>;

export function PickSavePath(arg1:string):Promise<string>;

export function PickUploadPaths():Promise<Array<string>>;

export function Poke(arg1:string,arg2:string):Promise<string>;

export function PokeForTab(arg1:string,arg2:string,arg3:string):Promise<string>;

export function PollForTab(arg1:string,arg2:netproto.PollRequest):Promise<netproto.PollState>;

export function PositionalInputPath():Promise<string>;

export function PreviewChannelAccessForTab(arg1:string,arg2:netproto.ChannelAccessPreview):Promise<authorization.ChannelAccessImpact>;

export function PrivateCallForTab(arg1:string,arg2:netproto.CallRequest):Promise<netproto.CallResult>;

export function PublishPositionForTab(arg1:string,arg2:netproto.PositionUpdate):Promise<string>;

export function ReadPositionalInput():Promise<main.PositionalInput>;

export function RecordRecent(arg1:string,arg2:string):Promise<void>;

export function RegenerateIdentity():Promise<string>;

export function RemoveRoleBanForTab(arg1:string,arg2:number):Promise<netproto.RoleBanRemoved>;

export function RenameIdentity(arg1:string,arg2:string):Promise<string>;

export function RoleChange(arg1:authorization.RoleChange):Promise<netproto.RoleChangeResult>;

export function RoleChangeForTab(arg1:string,arg2:authorization.RoleChange):Promise<netproto.RoleChangeResult>;

export function RoleChannelState(arg1:netproto.RoleChannelQuery):Promise<netproto.RoleChannelState>;

export function RoleChannelStateForTab(arg1:string,arg2:netproto.RoleChannelQuery):Promise<netproto.RoleChannelState>;

export function RoleMembers(arg1:authorization.MemberQuery):Promise<authorization.MemberPage>;

export function RoleMembersForTab(arg1:string,arg2:authorization.MemberQuery):Promise<authorization.MemberPage>;

export function RoleState(arg1:number):Promise<netproto.RoleState>;

export function RoleStateForTab(arg1:string,arg2:number):Promise<netproto.RoleState>;

export function SaveChatAttachment(arg1:number,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SaveChatAttachmentForTab(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string):Promise<string>;

export function SaveSettings(arg1:main.Settings):Promise<string>;

export function SendChat(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SendChatDelivered(arg1:string,arg2:string):Promise<string>;

export function SendChatDeliveredForTab(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SendChatForTab(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SendChatRead(arg1:string,arg2:string):Promise<string>;

export function SendChatReadForTab(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SendChatReply(arg1:string,arg2:string,arg3:string,arg4:number):Promise<string>;

export function SendChatReplyForTab(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<string>;

export function SendConversationForTab(arg1:string,arg2:string,arg3:string,arg4:string):Promise<number>;

export function SendICECandidate(arg1:string,arg2:string,arg3:number):Promise<void>;

export function SendICECandidateForTab(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function SendPrivateCallDescriptionForTab(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function SendTyping(arg1:number,arg2:string):Promise<string>;

export function SendTypingForTab(arg1:string,arg2:number,arg3:string):Promise<string>;

export function ServerBannerGet():Promise<netproto.ServerBannerData>;

export function ServerBannerGetForTab(arg1:string):Promise<netproto.ServerBannerData>;

export function ServerBannerSet(arg1:string):Promise<string>;

export function ServerBannerSetForTab(arg1:string,arg2:string):Promise<string>;

export function ServerFingerprint():Promise<string>;

export function ServerIconGet():Promise<netproto.ServerIconData>;

export function ServerIconGetForTab(arg1:string):Promise<netproto.ServerIconData>;

export function ServerIconSet(arg1:string):Promise<string>;

export function ServerIconSetForTab(arg1:string,arg2:string):Promise<string>;

export function ServerInfo():Promise<netproto.ServerInfoResponse>;

export function ServerInfoForTab(arg1:string):Promise<netproto.ServerInfoResponse>;

export function SessionInfoForTab(arg1:string):Promise<main.SessionInfo>;

export function SetActiveTab(arg1:string):Promise<void>;

export function SetAlwaysOnTop(arg1:boolean):Promise<void>;

export function SetAvatar(arg1:string):Promise<string>;

export function SetAvatarForTab(arg1:string,arg2:string):Promise<string>;

export function SetDebugFrames(arg1:boolean):Promise<void>;

export function SetHotkey(arg1:string,arg2:string):Promise<string>;

export function SetHotkeys(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SetMediaLimitsForTab(arg1:string,arg2:netproto.MediaLimits):Promise<netproto.MediaLimitsSaved>;

export function SetMemberVoice(arg1:netproto.MemberVoiceSet):Promise<netproto.MemberVoiceState>;

export function SetMemberVoiceForTab(arg1:string,arg2:netproto.MemberVoiceSet):Promise<netproto.MemberVoiceState>;

export function SetMuted(arg1:boolean):Promise<void>;

export function SetPTT(arg1:boolean):Promise<void>;

export function SetPrioritySpeaker(arg1:boolean):Promise<string>;

export function SetPrioritySpeakerForTab(arg1:string,arg2:boolean):Promise<string>;

export function SetRoleChannelIconForTab(arg1:string,arg2:number,arg3:string,arg4:number):Promise<netproto.RoleChannelIconSaved>;

export function SetScreenShare(arg1:boolean):Promise<string>;

export function SetScreenShareForTab(arg1:string,arg2:boolean):Promise<string>;

export function SetScreenShareQuality(arg1:boolean,arg2:number):Promise<string>;

export function SetScreenShareQualityForTab(arg1:string,arg2:boolean,arg3:number):Promise<string>;

export function SetServerConfig(arg1:netproto.ServerConfig):Promise<netproto.ServerConfig>;

export function SetServerConfigForTab(arg1:string,arg2:netproto.ServerConfig):Promise<netproto.ServerConfig>;

export function SetStatus(arg1:string,arg2:string):Promise<string>;

export function SetStatusForTab(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SetTrayVoiceState(arg1:boolean,arg2:boolean,arg3:boolean):Promise<void>;

export function SetVideoQuality(arg1:string):Promise<string>;

export function SetVideoQualityForTab(arg1:string,arg2:string):Promise<string>;

export function SetWindowOpacity(arg1:number):Promise<string>;

export function StopPrivateCallForTab(arg1:string,arg2:string):Promise<void>;

export function SubscribeChannels(arg1:Array<number>,arg2:boolean):Promise<string>;

export function SubscribeChannelsForTab(arg1:string,arg2:Array<number>,arg3:boolean):Promise<string>;

export function Subscriptions():Promise<Array<number>>;

export function SubscriptionsForTab(arg1:string):Promise<Array<number>>;

export function SwitchIdentity(arg1:string):Promise<string>;

export function SystemCPUPercent():Promise<number>;

export function TrayClearMentions():Promise<void>;

export function TrayMention():Promise<void>;

export function TrustServerFingerprint(arg1:string,arg2:string):Promise<string>;

export function UploadChatAttachment(arg1:number,arg2:string,arg3:string):Promise<string>;

export function UploadChatAttachmentForTab(arg1:string,arg2:number,arg3:string,arg4:string):Promise<string>;

export function UploadFile(arg1:number,arg2:string,arg3:string):Promise<string>;

export function UploadFileProgress(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string):Promise<string>;

export function UploadFileProgressForTab(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string,arg6:string):Promise<string>;

export function UploadPathProgress(arg1:string,arg2:number,arg3:string,arg4:string):Promise<string>;

export function UploadPathProgressForTab(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string):Promise<string>;

export function VerifyFile(arg1:number,arg2:string,arg3:string,arg4:string):Promise<boolean>;

export function VerifyFileForTab(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string):Promise<boolean>;

export function VideoStreamControlForTab(arg1:string,arg2:netproto.VideoStreamControl):Promise<netproto.VideoStreamResult>;

export function WebRTCAnswer(arg1:string):Promise<void>;

export function WebRTCAnswerForTab(arg1:string,arg2:string):Promise<void>;

export function WebRTCOffer(arg1:string,arg2:Array<netproto.TrackSlot>):Promise<string>;

export function WebRTCOfferForTab(arg1:string,arg2:string,arg3:Array<netproto.TrackSlot>):Promise<string>;

export function WhatsNew():Promise<string>;

export function WhisperSet(arg1:Array<string>,arg2:Array<number>,arg3:boolean):Promise<string>;

export function WhisperSetForTab(arg1:string,arg2:Array<string>,arg3:Array<number>,arg4:boolean):Promise<string>;
