"""Development-only static speech rendering. Never imported or run by noXa.

Usage: python tools/generate-speech.py --models .cache/noxa-speech-models [--events user_join user_leave]
English uses piper-tts==1.4.2 and numpy in an isolated environment.
German AN06 authoring is handled by generate-an06-speech.py.
"""
import argparse
import hashlib
import importlib.metadata
import io
import json
import wave
from pathlib import Path


def sha256(path):
    digest = hashlib.sha256()
    with path.open('rb') as source:
        for chunk in iter(lambda: source.read(8 * 1024 * 1024), b''):
            digest.update(chunk)
    return digest.hexdigest()


def master_samples(samples, rate, settings, language):
    """One speech mastering contract shared by both offline providers."""
    import numpy as np
    samples = np.asarray(samples, dtype=np.float64)
    if samples.ndim != 1 or rate not in (22050, 24000, 48000) or not np.isfinite(samples).all():
        raise ValueError('Invalid sample rate or non-finite speech samples')
    active = np.flatnonzero(np.abs(samples) > settings['silence_threshold'])
    if not len(active):
        raise ValueError('Empty speech clip')
    local = settings['de'] if language == 'de' else {}
    leading = round(rate * local.get('leading_padding_ms', settings['edge_padding_ms']) / 1000)
    trailing = round(rate * local.get('trailing_padding_ms', settings['edge_padding_ms']) / 1000)
    samples = samples[max(0, active[0]-leading):min(len(samples), active[-1]+trailing+1)].copy()
    duration = len(samples) / rate
    if not .5 <= duration <= 6:
        raise ValueError(f'Speech duration outside 0.5–6 seconds: {duration}')
    samples -= samples.mean()
    ramp = np.linspace(0, 1, round(rate * local.get('endpoint_fade_ms', settings['endpoint_fade_ms']) / 1000))
    samples[:len(ramp)] *= ramp
    samples[-len(ramp):] *= ramp[::-1]
    rms = np.sqrt(np.mean(samples**2))
    peak = np.max(np.abs(samples))
    if not np.isfinite(rms) or not np.isfinite(peak) or rms <= 0 or peak <= 0:
        raise ValueError('Speech has no finite energy after DC removal and fades')
    gain = min(10**(settings['target_rms_dbfs']/20) / rms,
               settings['peak_ceiling'] / peak)
    pcm = np.round(samples * gain * 32767).astype('<i2')
    measured = pcm.astype(float) / 32768
    measured_rms = float(np.sqrt(np.mean(measured**2)))
    if not np.isfinite(measured_rms) or measured_rms <= 0 or not np.any(pcm):
        raise ValueError('Speech is silent or non-finite after quantization')
    if np.max(np.abs(measured)) > .1151 or pcm[0] != 0 or pcm[-1] != 0 or abs(measured.mean()) >= .0001:
        raise ValueError('Speech level, endpoint or DC validation failed')
    return pcm, {'duration': duration, 'sampleRate': rate,
                 'peak': float(np.max(np.abs(measured))),
                 'rmsDB': float(20*np.log10(measured_rms))}


def write_recording(path, pcm, rate):
    path.parent.mkdir(parents=True, exist_ok=True)
    with wave.open(str(path), 'wb') as wav:
        wav.setnchannels(1)
        wav.setsampwidth(2)
        wav.setframerate(rate)
        wav.writeframes(pcm.tobytes())
    if path.stat().st_size != 44 + len(pcm)*2:
        raise ValueError(f'Unexpected WAV layout: {path}')


def write_catalog(root, lines, metrics):
    catalog = '// Generated by tools/generate-speech.py. Static assets only.\nexport const SPEECH_ASSETS = {\n'
    for language, phrases in lines.items():
        catalog += f'    {language}: {{\n'
        for event, text in phrases.items():
            metric = metrics[f'{language}/{event}']
            if metric['text'] != text:
                raise ValueError(f'Regenerate changed text: {language}/{event}')
            transcript = json.dumps(text, ensure_ascii=False)
            catalog += f'        {event}: {{ url: new URL("./assets/speech/{language}/{event}.wav", import.meta.url).href, duration: {metric["duration"]}, transcript: {transcript} }},\n'
        catalog += '    },\n'
    catalog += '};\n'
    (root / 'client/frontend/src/speech-catalog.js').write_text(catalog, encoding='utf-8')

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--models', type=Path, default=Path('.cache/noxa-speech-models'))
    parser.add_argument('--events', nargs='+', help='Render only these events; retain all other WAVs and metrics')
    parser.add_argument('--languages', nargs='+', choices=['en'], default=['en'])
    parser.add_argument('--skip-catalog', action='store_true', help='Defer catalog publication until German authoring is complete')
    parser.add_argument('--catalog-only', action='store_true', help='Publish the catalog from complete, reviewed metrics without inference')
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    out = root / 'client/frontend/src/assets/speech'
    lines = json.loads((Path(__file__).parent / 'speech-lines.json').read_text(encoding='utf-8'))
    if args.events and set(args.events) - set(lines['en']):
        parser.error('Unknown speech event')
    provenance = json.loads((out / 'provenance.json').read_text(encoding='utf-8'))
    metrics = json.loads((out / 'metrics.json').read_text(encoding='utf-8'))
    if args.catalog_only:
        write_catalog(root, lines, metrics)
        return
    import numpy as np
    from piper import PiperVoice, SynthesisConfig
    if importlib.metadata.version('piper-tts') != provenance['authoring']['en']['version']:
        raise ValueError('Install the pinned piper-tts version')
    model_provenance = json.loads((args.models / 'provenance.json').read_text(encoding='utf-8'))
    if model_provenance.get('providers', {}).get('en') != provenance['providers']['en']:
        raise ValueError('Download the current English authoring model first')
    for name, digest in provenance['checksums'].items():
        if name.startswith('en.') and sha256(args.models / name) != digest:
            raise ValueError(f'Checksum mismatch: {name}')
    voice = PiperVoice.load(str(args.models / 'en.onnx'))
    settings = provenance['authoring']
    for event, text in lines['en'].items():
        if args.events and event not in args.events:
            if metrics[f'en/{event}']['text'] != text:
                raise ValueError(f'Regenerate changed text: en/{event}')
            continue
        raw = io.BytesIO()
        with wave.open(raw, 'wb') as wav:
            voice.synthesize_wav(text, wav, syn_config=SynthesisConfig(
                length_scale=settings['length_scale'], noise_scale=settings['noise_scale'],
                noise_w_scale=settings['noise_w_scale']))
        raw.seek(0)
        with wave.open(raw, 'rb') as wav:
            if wav.getnchannels() != 1 or wav.getsampwidth() != 2:
                raise ValueError('Expected mono PCM16 Piper output')
            rate = wav.getframerate()
            samples = np.frombuffer(wav.readframes(wav.getnframes()), dtype='<i2').astype(np.float64) / 32768
        pcm, measured = master_samples(samples, rate, settings, 'en')
        path = out / 'en' / (event + '.wav')
        write_recording(path, pcm, rate)
        metrics[f'en/{event}'] = {'title': f'noXa — {event}', 'text': text,
                                 **measured, 'sha256': sha256(path)}
        print('en', event, round(measured['duration'], 3), flush=True)
    (out / 'metrics.json').write_text(json.dumps(metrics, indent=2, ensure_ascii=False, allow_nan=False)+'\n', encoding='utf-8')
    if not args.skip_catalog:
        write_catalog(root, lines, metrics)
    (out / 'en-MODEL_CARD').write_bytes((args.models / 'en-MODEL_CARD').read_bytes())


if __name__ == '__main__':
    main()
