"""Development-only static speech rendering. Never imported or run by VOICX.

Usage: python tools/generate-speech.py --models temp/sound-runtime/speech-models
Requires piper-tts==1.4.2 and numpy in an isolated environment.
Model directory contains en.onnx, de.onnx, matching .json files and provenance.json.
"""
import argparse
import hashlib
import io
import json
import wave
from pathlib import Path
import numpy as np
from piper import PiperVoice, SynthesisConfig

parser = argparse.ArgumentParser()
parser.add_argument('--models', type=Path, required=True)
args = parser.parse_args()
root = Path(__file__).resolve().parents[1]
out = root / 'client/frontend/src/assets/speech'
lines = json.loads((Path(__file__).parent / 'speech-lines.json').read_text(encoding='utf-8'))
assets, metrics = {}, {}
for language, phrases in lines.items():
    voice = PiperVoice.load(str(args.models / (language + '.onnx')))
    (out / language).mkdir(parents=True, exist_ok=True)
    assets[language] = {}
    for event, text in phrases.items():
        raw = io.BytesIO()
        with wave.open(raw, 'wb') as wav:
            voice.synthesize_wav(text, wav, syn_config=SynthesisConfig(length_scale=.96, noise_scale=.45, noise_w_scale=.6))
        raw.seek(0)
        with wave.open(raw, 'rb') as wav:
            assert wav.getnchannels() == 1 and wav.getsampwidth() == 2
            rate = wav.getframerate()
            samples = np.frombuffer(wav.readframes(wav.getnframes()), dtype='<i2').astype(np.float64) / 32768
        assert rate in (22050, 24000, 48000) and np.isfinite(samples).all()
        active = np.flatnonzero(np.abs(samples) > .002)
        assert len(active), f'{language}/{event}: empty clip'
        # Preserve consonant edges with 25ms padding; remove neural-model trailing silence.
        pad = round(rate * .025)
        samples = samples[max(0, active[0]-pad):min(len(samples), active[-1]+pad+1)].copy()
        samples -= samples.mean()
        ramp = np.linspace(0, 1, round(rate*.005))
        samples[:len(ramp)] *= ramp
        samples[-len(ramp):] *= ramp[::-1]
        rms = np.sqrt(np.mean(samples**2))
        gain = min(10**(-31/20) / rms, .115 / np.max(np.abs(samples)))
        pcm = np.round(samples * gain * 32767).astype('<i2')
        measured = pcm.astype(float) / 32768
        duration = len(pcm) / rate
        assert .5 <= duration <= 6, f'{language}/{event}: duration {duration}'
        assert np.max(np.abs(measured)) <= .1151 and pcm[0] == 0 and pcm[-1] == 0
        assert abs(measured.mean()) < .0001
        path = out / language / (event + '.wav')
        with wave.open(str(path), 'wb') as wav:
            wav.setnchannels(1); wav.setsampwidth(2); wav.setframerate(rate); wav.writeframes(pcm.tobytes())
        assert path.stat().st_size == 44 + len(pcm)*2
        assets[language][event] = duration
        metrics[f'{language}/{event}'] = {'text':text,'duration':duration,'sampleRate':rate,'peak':float(np.max(np.abs(measured))), 'rmsDB':float(20*np.log10(np.sqrt(np.mean(measured**2)))),'sha256':hashlib.sha256(path.read_bytes()).hexdigest()}
        print(language, event, round(duration, 3), flush=True)

catalog = '// Generated by tools/generate-speech.py. Static assets only.\nexport const SPEECH_ASSETS = {\n'
for language, events in assets.items():
    catalog += f'    {language}: {{\n'
    for event, duration in events.items():
        catalog += f'        {event}: {{ url: new URL("./assets/speech/{language}/{event}.wav", import.meta.url).href, duration: {duration} }},\n'
    catalog += '    },\n'
catalog += '};\n'
(root / 'client/frontend/src/speech-catalog.js').write_text(catalog, encoding='utf-8')
(out / 'metrics.json').write_text(json.dumps(metrics, indent=2, ensure_ascii=False)+'\n', encoding='utf-8')
(out / 'provenance.json').write_text((args.models/'provenance.json').read_text(), encoding='utf-8')
for language in assets:
    (out / (language+'-MODEL_CARD')).write_bytes((args.models/(language+'-MODEL_CARD')).read_bytes())
